Add custom php settings to roundcubemail php-fpm pool
NethServer/nethserver-roundcubemail-next pull request #5
Opened 2022-05-17 14:19 UTC by stephdl

The PR attempts to adjust php settings to the php-fpm pool of rouncubemail and enable the roundcubemail mariadb server at boot 

```
roundcubemail=configuration
    MaxExecutionTime=0
    MaxFileUploads=20
    MemoryLimit=512
    PluginsList=managesieve,markasjunk
    PostMaxSize=32
    Server=localhost
    UploadMaxFilesize=32
    access=public
    skin=larry
```

https://github.com/NethServer/dev/issues/6666

2022-05-18 11:55 UTC, gsanchietti reviewed
If you want, you can omit [root/etc/e-smith/db/configuration/defaults/rh-mariadb105-mariadb@roundcubemail/access](https://github.com/NethServer/nethserver-roundcubemail-next/pull/5/files#diff-ac11fdff2c8339640b93afcddbc8ce8be176408ab47fa72605950210c51c4077)

2022-05-18 11:55 UTC, gsanchietti commented on root/etc/e-smith/templates/etc/opt/rh/rh-php73/php-fpm.d/000-roundcubemail.conf/20PhpSettings
> +            my $UpMaxFileSize = $db->get_prop('roundcubemail','UploadMaxFilesize') || '32';
The indentation is a bit messy :)

2022-05-18 11:55 UTC, gsanchietti commented on root/etc/e-smith/db/configuration/defaults/roundcubemail/MaxExecutionTime
> +0
Maybe a value around 300 is better.

2022-05-18 13:34 UTC, stephdl commented on root/etc/e-smith/templates/etc/opt/rh/rh-php73/php-fpm.d/000-roundcubemail.conf/20PhpSettings
> +            my $UpMaxFileSize = $db->get_prop('roundcubemail','UploadMaxFilesize') || '32';
done

2022-05-18 13:36 UTC, stephdl commented on root/etc/e-smith/db/configuration/defaults/roundcubemail/MaxExecutionTime
> +0
done

2022-05-18 14:29 UTC, gsanchietti requested changes

2022-05-18 14:29 UTC, gsanchietti commented on root/etc/e-smith/events/actions/nethserver-rouncubemail-next-clean-cache
> +/usr/bin/rm `/usr/bin/find  /var/opt/rh/rh-php*/lib/php/opcache/ -name 'roundcubemail'` -rf
Please use find syntax:
```
find <path> -name <pattern> -delete
```

2022-05-18 15:06 UTC, stephdl commented on root/etc/e-smith/events/actions/nethserver-rouncubemail-next-clean-cache
> +/usr/bin/rm `/usr/bin/find  /var/opt/rh/rh-php*/lib/php/opcache/ -name 'roundcubemail'` -rf
I cannot remove not empty folder :'(

2022-05-18 15:16 UTC, stephdl commented on root/etc/e-smith/events/actions/nethserver-rouncubemail-next-clean-cache
> +/usr/bin/rm `/usr/bin/find  /var/opt/rh/rh-php*/lib/php/opcache/ -name 'roundcubemail'` -rf
/usr/bin/find  /var/opt/rh/rh-php*/lib/php/opcache/ -name 'roundcubemail' -exec rm -rf {} +

2022-05-19 07:39 UTC, gsanchietti approved these changes

2022-05-19 12:35 UTC, merged